project new C:/timSSD/nand13/pcores/nand_01_v1_00_a/devl/projnav/nand_01.ise;
project set family virtex5;
project set device xc5vlx110t;
project set package ff1136;
project set speed -1;
project set top_level_module_type HDL;
project set synthesis_tool "XST (VHDL/Verilog)";
project set simulator "Modelsim-SE Mixed";
lib_vhdl new nand_01_v1_00_a;
xfile add C:/timSSD/nand13//pcores/nand_01_v1_00_a/hdl/verilog/nand_01.v;
project close;
